"""
Layer 3: SVM Trade-Veto Filter (RBF Kernel)
Maintains rolling feature matrix [price_delta, rolling_volatility, garch_forecast],
fits scikit-learn.svm.SVC(kernel='rbf', gamma=0.0001, C=1.0),
and vetoes conflicting directional trades.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Tuple
import logging
import joblib
import numpy as np
import pandas as pd
from sklearn.svm import SVC

from .config import SVMConfig
from .garch_engine import DirectionalSignal

logger = logging.getLogger("algo_vpin_dhan.svm_filter")


@dataclass
class SVMVetoDecision:
    """Decision output from SVM veto filter"""
    is_vetoed: bool
    svm_prediction: int         # +1 (Bullish) or -1 (Bearish)
    garch_signal: DirectionalSignal
    final_action: DirectionalSignal
    reason: str
    decision_margin: float      # Distance from separating hyperplane
    model_trained: bool


class SVMTradeFilter:
    """
    Rolling RBF-kernel SVM classifier designed to veto false breakout signals
    generated by Layer 2 GARCH(1,1).
    """

    def __init__(self, config: Optional[SVMConfig] = None):
        self.config = config or SVMConfig()
        self.kernel = self.config.kernel
        self.c_param = self.config.c_param
        self.gamma = self.config.gamma
        self.max_samples = self.config.max_training_samples
        self.retrain_interval = self.config.retrain_interval_bars

        # Rolling storage for features and targets
        self.feature_history: List[List[float]] = []
        self.target_history: List[int] = []
        self.price_history: List[float] = []

        # Tracking pending feature vector waiting for forward return label
        self._pending_feature: Optional[List[float]] = None
        self._pending_price: Optional[float] = None

        # Trained SVC model
        self.model: Optional[SVC] = None
        self.bars_since_retrain = 0
        self.is_trained = False

    def build_feature_vector(
        self,
        price_delta: float,
        rolling_volatility: float,
        garch_forecast: float
    ) -> List[float]:
        """
        Constructs the 3-element feature vector:
        [price_delta, rolling_volatility, garch_forecast]
        """
        return [
            float(price_delta),
            float(rolling_volatility),
            float(garch_forecast)
        ]

    def update_bar(
        self,
        current_price: float,
        price_delta: float,
        rolling_vol: float,
        garch_forecast: float
    ):
        """
        Updates the feature-target training set when a new 1-min bar closes.
        Label y_t = +1 if P_{t+1} > P_t else -1
        """
        # Resolve pending feature from previous bar using current price
        if self._pending_feature is not None and self._pending_price is not None:
            forward_ret = current_price - self._pending_price
            target = 1 if forward_ret >= 0 else -1

            self.feature_history.append(self._pending_feature)
            self.target_history.append(target)

            # Keep buffer bounded to lookback window
            if len(self.feature_history) > self.max_samples:
                self.feature_history = self.feature_history[-self.max_samples:]
                self.target_history = self.target_history[-self.max_samples:]

        # Stage current feature vector for next bar's forward return
        self._pending_feature = self.build_feature_vector(price_delta, rolling_vol, garch_forecast)
        self._pending_price = current_price
        self.price_history.append(current_price)

        self.bars_since_retrain += 1
        if self.bars_since_retrain >= self.retrain_interval:
            self.train_model()

    def train_model(self) -> bool:
        """
        Trains the SVC(kernel='rbf', gamma=0.0001, C=1.0) on rolling feature history.
        """
        if len(self.feature_history) < 30:
            return False

        # Check for class diversity
        unique_classes = set(self.target_history)
        if len(unique_classes) < 2:
            return False

        X = np.array(self.feature_history, dtype=np.float64)
        y = np.array(self.target_history, dtype=np.int32)

        try:
            model = SVC(
                kernel=self.kernel,
                C=self.c_param,
                gamma=self.gamma,
                decision_function_shape="ovr"
            )
            model.fit(X, y)
            self.model = model
            self.is_trained = True
            self.bars_since_retrain = 0
            self.save_model()
            return True
        except Exception:
            return False

    def save_model(self, file_path: Optional[Path] = None):
        """Saves trained SVM model to disk using joblib"""
        if not self.is_trained or self.model is None:
            return
        try:
            target_path = file_path or (Path(__file__).parent / "models" / "svm_model.joblib")
            target_path.parent.mkdir(parents=True, exist_ok=True)
            joblib.dump({
                "model": self.model,
                "feature_history": self.feature_history,
                "target_history": self.target_history,
                "is_trained": self.is_trained
            }, target_path)
            logger.info(f"[SVM Engine] Saved trained model to {target_path.name}")
        except Exception as e:
            logger.warning(f"Could not save SVM model: {e}")

    def load_model(self, file_path: Optional[Path] = None) -> bool:
        """Loads pre-trained SVM model from disk if available"""
        target_path = file_path or (Path(__file__).parent / "models" / "svm_model.joblib")
        if not target_path.exists():
            return False
        try:
            payload = joblib.load(target_path)
            self.model = payload["model"]
            self.feature_history = payload.get("feature_history", [])
            self.target_history = payload.get("target_history", [])
            self.is_trained = payload.get("is_trained", True)
            logger.info(f"[SVM Engine] Loaded pre-trained SVM model ({len(self.feature_history)} historical samples)")
            return True
        except Exception as e:
            logger.warning(f"Could not load pre-trained SVM model: {e}")
            return False

    def predict(self, feature_vector: List[float]) -> Tuple[int, float]:
        """
        Generates SVM forward directional prediction (+1 / -1) and decision distance.
        """
        if not self.is_trained or self.model is None:
            # Neutral / Pass-through if not yet trained
            return 1, 0.0

        x_arr = np.array([feature_vector], dtype=np.float64)
        try:
            pred = int(self.model.predict(x_arr)[0])
            distance = float(self.model.decision_function(x_arr)[0])
            return pred, distance
        except Exception:
            return 1, 0.0

    def evaluate_signal(
        self,
        garch_signal: DirectionalSignal,
        price_delta: float,
        rolling_vol: float,
        garch_forecast: float
    ) -> SVMVetoDecision:
        """
        Evaluates Layer 2 GARCH signal against Layer 3 SVM trade-veto filter:
        - If GARCH signals BUY but SVM predicts -1 -> Abort/Veto trade
        - If GARCH signals SELL but SVM predicts +1 -> Abort/Veto trade
        - If GARCH signals HOLD -> No trade
        """
        if garch_signal == DirectionalSignal.HOLD:
            return SVMVetoDecision(
                is_vetoed=False,
                svm_prediction=0,
                garch_signal=garch_signal,
                final_action=DirectionalSignal.HOLD,
                reason="GARCH is neutral (HOLD)",
                decision_margin=0.0,
                model_trained=self.is_trained
            )

        features = self.build_feature_vector(price_delta, rolling_vol, garch_forecast)
        svm_pred, margin = self.predict(features)

        # Apply Veto Rules:
        if garch_signal == DirectionalSignal.BUY and svm_pred == -1:
            return SVMVetoDecision(
                is_vetoed=True,
                svm_prediction=-1,
                garch_signal=garch_signal,
                final_action=DirectionalSignal.HOLD,
                reason="VETO: GARCH signaled BUY (+1) but SVM predicted Bearish (-1)",
                decision_margin=margin,
                model_trained=self.is_trained
            )

        if garch_signal == DirectionalSignal.SELL and svm_pred == 1:
            return SVMVetoDecision(
                is_vetoed=True,
                svm_prediction=1,
                garch_signal=garch_signal,
                final_action=DirectionalSignal.HOLD,
                reason="VETO: GARCH signaled SELL (-1) but SVM predicted Bullish (+1)",
                decision_margin=margin,
                model_trained=self.is_trained
            )

        # Signals agree or model warm-up
        return SVMVetoDecision(
            is_vetoed=False,
            svm_prediction=svm_pred,
            garch_signal=garch_signal,
            final_action=garch_signal,
            reason=f"APPROVED: GARCH {garch_signal.value} confirmed by SVM ({svm_pred:+d})",
            decision_margin=margin,
            model_trained=self.is_trained
        )

    def warm_up_with_historical(self, features: List[List[float]], targets: List[int]):
        """
        Pre-seeds SVM history from historical bar dataset.
        """
        self.feature_history.extend(features)
        self.target_history.extend(targets)
        if len(self.feature_history) > self.max_samples:
            self.feature_history = self.feature_history[-self.max_samples:]
            self.target_history = self.target_history[-self.max_samples:]
        self.train_model()
